// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Tivizi",
            "url": "https://fora.run",
            "email": "tivizi@163.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/resources": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "主站管理"
                ],
                "summary": "新的资源文件",
                "parameters": [
                    {
                        "description": "NewResourceReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.NewResourceReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/admin/resources/{rid}/raw": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "主站管理"
                ],
                "summary": "修改资源文件内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "资源文件ID",
                        "name": "rid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchResourceRawReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.PatchResourceRawReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/admin/sites": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "主站管理"
                ],
                "summary": "列出所有站点"
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "主站管理"
                ],
                "summary": "新站点",
                "parameters": [
                    {
                        "description": "NewSiteReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.NewSiteReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/admin/sites/:site/user/:user": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "主站管理"
                ],
                "summary": "绑定用户和站点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "站点ID",
                        "name": "siteID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/api/v1/site/accounts": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点功能"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "RegisterAccountReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/site.RegisterAccountReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/site/accounts/active": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点功能"
                ],
                "summary": "发送激活账户邮件"
            }
        },
        "/api/v1/site/accounts/sessions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点功能"
                ],
                "summary": "用户新会话",
                "parameters": [
                    {
                        "description": "NewSessionReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/site.NewSessionReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/site/accounts/{uid}/passwd/{passwd}": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点功能"
                ],
                "summary": "发送重置密码邮件"
            }
        },
        "/api/v1/site/admin/bbs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "列出站点所有论坛版块"
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "新的论坛版块",
                "parameters": [
                    {
                        "description": "NewBBSReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.NewBBSReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/site/admin/bbs/css": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "更新站点论坛CSS"
            }
        },
        "/api/v1/site/admin/pages": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "新的页面",
                "parameters": [
                    {
                        "description": "NewPageReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.NewPageReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/site/admin/pages/{pageID}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "修改页面",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页面ID",
                        "name": "pageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "NewPageReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.NewPageReq"
                        }
                    }
                ]
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "删除页面",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页面ID",
                        "name": "pageID",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/api/v1/site/admin/sites": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "更新站点",
                "parameters": [
                    {
                        "description": "UpdateSiteReq",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UpdateSiteReq"
                        }
                    }
                ]
            }
        },
        "/api/v1/site/bbs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点功能"
                ],
                "summary": "列出站点所有论坛版块"
            }
        },
        "/api/v1/site/bbs/:bbs/threads": {
            "post": {
                "tags": [
                    "站点功能"
                ],
                "summary": "新帖子"
            }
        },
        "/api/v1/site/sites": {
            "post": {
                "tags": [
                    "站点功能"
                ],
                "summary": "新站点"
            }
        },
        "/api/v1/site/threads/:tid/reply": {
            "post": {
                "tags": [
                    "站点功能"
                ],
                "summary": "新帖子回复"
            }
        }
    },
    "definitions": {
        "admin.NewBBSReq": {
            "type": "object",
            "required": [
                "name",
                "parentID"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "type": "string"
                }
            }
        },
        "admin.NewPageReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "alias": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "footer": {
                    "type": "string"
                },
                "header": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "admin.NewResourceReq": {
            "type": "object",
            "required": [
                "contentType",
                "name",
                "raw"
            ],
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                }
            }
        },
        "admin.NewSiteReq": {
            "type": "object",
            "required": [
                "host",
                "name",
                "userID"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "admin.PatchResourceRawReq": {
            "type": "object",
            "required": [
                "resourceString"
            ],
            "properties": {
                "resourceString": {
                    "type": "string"
                }
            }
        },
        "admin.UpdateSiteReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "footer": {
                    "type": "string"
                },
                "header": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "site.NewSessionReq": {
            "type": "object",
            "required": [
                "password",
                "user"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "site.RegisterAccountReq": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "fora.run",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "FORARUN 自助建站系统开放接口文档",
	Description: "轻量级自助建站系统，随时随地维护站点",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
